/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPublishingRouteImport } from './routes/_authenticated/publishing'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsBatchRouteImport } from './routes/_authenticated/products.batch'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as ApiPublicEbayCallbackRouteImport } from './routes/api/public/ebay/callback'
import { Route as ApiPublicEbayImagePhotoIdRouteImport } from './routes/api/public/ebay/image.$photoId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishingRoute = AuthenticatedPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsBatchRoute =
  AuthenticatedProductsBatchRouteImport.update({
    id: '/batch',
    path: '/batch',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProductsRoute,
} as any)
const ApiPublicEbayCallbackRoute = ApiPublicEbayCallbackRouteImport.update({
  id: '/api/public/ebay/callback',
  path: '/api/public/ebay/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEbayImagePhotoIdRoute =
  ApiPublicEbayImagePhotoIdRouteImport.update({
    id: '/api/public/ebay/image/$photoId',
    path: '/api/public/ebay/image/$photoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/publishing': typeof AuthenticatedPublishingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/batch': typeof AuthenticatedProductsBatchRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/api/public/ebay/callback': typeof ApiPublicEbayCallbackRoute
  '/api/public/ebay/image/$photoId': typeof ApiPublicEbayImagePhotoIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/publishing': typeof AuthenticatedPublishingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/batch': typeof AuthenticatedProductsBatchRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/api/public/ebay/callback': typeof ApiPublicEbayCallbackRoute
  '/api/public/ebay/image/$photoId': typeof ApiPublicEbayImagePhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/publishing': typeof AuthenticatedPublishingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/batch': typeof AuthenticatedProductsBatchRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/api/public/ebay/callback': typeof ApiPublicEbayCallbackRoute
  '/api/public/ebay/image/$photoId': typeof ApiPublicEbayImagePhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/intake'
    | '/locations'
    | '/products'
    | '/publishing'
    | '/settings'
    | '/products/$id'
    | '/products/batch'
    | '/products/new'
    | '/products/'
    | '/api/public/ebay/callback'
    | '/api/public/ebay/image/$photoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/intake'
    | '/locations'
    | '/publishing'
    | '/settings'
    | '/'
    | '/products/$id'
    | '/products/batch'
    | '/products/new'
    | '/products'
    | '/api/public/ebay/callback'
    | '/api/public/ebay/image/$photoId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/intake'
    | '/_authenticated/locations'
    | '/_authenticated/products'
    | '/_authenticated/publishing'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/batch'
    | '/_authenticated/products/new'
    | '/_authenticated/products/'
    | '/api/public/ebay/callback'
    | '/api/public/ebay/image/$photoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicEbayCallbackRoute: typeof ApiPublicEbayCallbackRoute
  ApiPublicEbayImagePhotoIdRoute: typeof ApiPublicEbayImagePhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishing': {
      id: '/_authenticated/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AuthenticatedPublishingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/batch': {
      id: '/_authenticated/products/batch'
      path: '/batch'
      fullPath: '/products/batch'
      preLoaderRoute: typeof AuthenticatedProductsBatchRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/api/public/ebay/callback': {
      id: '/api/public/ebay/callback'
      path: '/api/public/ebay/callback'
      fullPath: '/api/public/ebay/callback'
      preLoaderRoute: typeof ApiPublicEbayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ebay/image/$photoId': {
      id: '/api/public/ebay/image/$photoId'
      path: '/api/public/ebay/image/$photoId'
      fullPath: '/api/public/ebay/image/$photoId'
      preLoaderRoute: typeof ApiPublicEbayImagePhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsBatchRoute: typeof AuthenticatedProductsBatchRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsBatchRoute: AuthenticatedProductsBatchRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedPublishingRoute: typeof AuthenticatedPublishingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedPublishingRoute: AuthenticatedPublishingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicEbayCallbackRoute: ApiPublicEbayCallbackRoute,
  ApiPublicEbayImagePhotoIdRoute: ApiPublicEbayImagePhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
