-- Applied directly by Lovable Cloud on 2026-08-02.
--
-- The canonical, additive schema is already defined in the earlier migration:
--   20260802013000_ai_listing_v2.sql
--
-- This migration intentionally remains a no-op in source control so a fresh
-- environment does not attempt to create the same RLS policies and triggers a
-- second time. Lovable Cloud has already recorded this migration as applied.
